name: github-actions-workflow
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
      - uses: microsoft/playwright-github-action@v1

      - name: Install dependencies and run tests
        run: npm install
        
      - run: npx playwright install  
      
      - name: Run tests
        run: npm run tests:cross-browsers